// Country codes with flags and names
export const countryCodes = [
  { code: '+966', name: 'السعودية', nameEn: 'Saudi Arabia', flag: '🇸🇦' },
  { code: '+965', name: 'الكويت', nameEn: 'Kuwait', flag: '🇰🇼' },
  { code: '+971', name: 'الإمارات', nameEn: 'UAE', flag: '🇦🇪' },
  { code: '+974', name: 'قطر', nameEn: 'Qatar', flag: '🇶🇦' },
  { code: '+973', name: 'البحرين', nameEn: 'Bahrain', flag: '🇧🇭' },
  { code: '+968', name: 'عمان', nameEn: 'Oman', flag: '🇴🇲' },
  { code: '+961', name: 'لبنان', nameEn: 'Lebanon', flag: '🇱🇧' },
  { code: '+962', name: 'الأردن', nameEn: 'Jordan', flag: '🇯🇴' },
  { code: '+963', name: 'سوريا', nameEn: 'Syria', flag: '🇸🇾' },
  { code: '+964', name: 'العراق', nameEn: 'Iraq', flag: '🇮🇶' },
  { code: '+20', name: 'مصر', nameEn: 'Egypt', flag: '🇪🇬' },
  { code: '+212', name: 'المغرب', nameEn: 'Morocco', flag: '🇲🇦' },
  { code: '+213', name: 'الجزائر', nameEn: 'Algeria', flag: '🇩🇿' },
  { code: '+216', name: 'تونس', nameEn: 'Tunisia', flag: '🇹🇳' },
  { code: '+218', name: 'ليبيا', nameEn: 'Libya', flag: '🇱🇾' },
  { code: '+249', name: 'السودان', nameEn: 'Sudan', flag: '🇸🇩' },
  { code: '+967', name: 'اليمن', nameEn: 'Yemen', flag: '🇾🇪' },
  { code: '+970', name: 'فلسطين', nameEn: 'Palestine', flag: '🇵🇸' },
  { code: '+1', name: 'الولايات المتحدة', nameEn: 'USA', flag: '🇺🇸' },
  { code: '+1', name: 'كندا', nameEn: 'Canada', flag: '🇨🇦' },
  { code: '+44', name: 'المملكة المتحدة', nameEn: 'UK', flag: '🇬🇧' },
  { code: '+33', name: 'فرنسا', nameEn: 'France', flag: '🇫🇷' },
  { code: '+49', name: 'ألمانيا', nameEn: 'Germany', flag: '🇩🇪' },
  { code: '+39', name: 'إيطاليا', nameEn: 'Italy', flag: '🇮🇹' },
  { code: '+34', name: 'إسبانيا', nameEn: 'Spain', flag: '🇪🇸' },
  { code: '+31', name: 'هولندا', nameEn: 'Netherlands', flag: '🇳🇱' },
  { code: '+32', name: 'بلجيكا', nameEn: 'Belgium', flag: '🇧🇪' },
  { code: '+41', name: 'سويسرا', nameEn: 'Switzerland', flag: '🇨🇭' },
  { code: '+46', name: 'السويد', nameEn: 'Sweden', flag: '🇸🇪' },
  { code: '+47', name: 'النرويج', nameEn: 'Norway', flag: '🇳🇴' },
  { code: '+45', name: 'الدنمارك', nameEn: 'Denmark', flag: '🇩🇰' },
  { code: '+358', name: 'فنلندا', nameEn: 'Finland', flag: '🇫🇮' },
  { code: '+7', name: 'روسيا', nameEn: 'Russia', flag: '🇷🇺' },
  { code: '+86', name: 'الصين', nameEn: 'China', flag: '🇨🇳' },
  { code: '+81', name: 'اليابان', nameEn: 'Japan', flag: '🇯🇵' },
  { code: '+82', name: 'كوريا الجنوبية', nameEn: 'South Korea', flag: '🇰🇷' },
  { code: '+91', name: 'الهند', nameEn: 'India', flag: '🇮🇳' },
  { code: '+92', name: 'باكستان', nameEn: 'Pakistan', flag: '🇵🇰' },
  { code: '+880', name: 'بنغلاديش', nameEn: 'Bangladesh', flag: '🇧🇩' },
  { code: '+62', name: 'إندونيسيا', nameEn: 'Indonesia', flag: '🇮🇩' },
  { code: '+60', name: 'ماليزيا', nameEn: 'Malaysia', flag: '🇲🇾' },
  { code: '+65', name: 'سنغافورة', nameEn: 'Singapore', flag: '🇸🇬' },
  { code: '+66', name: 'تايلاند', nameEn: 'Thailand', flag: '🇹🇭' },
  { code: '+84', name: 'فيتنام', nameEn: 'Vietnam', flag: '🇻🇳' },
  { code: '+61', name: 'أستراليا', nameEn: 'Australia', flag: '🇦🇺' },
  { code: '+64', name: 'نيوزيلندا', nameEn: 'New Zealand', flag: '🇳🇿' },
  { code: '+27', name: 'جنوب أفريقيا', nameEn: 'South Africa', flag: '🇿🇦' },
  { code: '+234', name: 'نيجيريا', nameEn: 'Nigeria', flag: '🇳🇬' },
  { code: '+254', name: 'كينيا', nameEn: 'Kenya', flag: '🇰🇪' },
  { code: '+90', name: 'تركيا', nameEn: 'Turkey', flag: '🇹🇷' },
  { code: '+98', name: 'إيران', nameEn: 'Iran', flag: '🇮🇷' },
  { code: '+972', name: 'إسرائيل', nameEn: 'Israel', flag: '🇮🇱' },
  { code: '+351', name: 'البرتغال', nameEn: 'Portugal', flag: '🇵🇹' },
  { code: '+353', name: 'أيرلندا', nameEn: 'Ireland', flag: '🇮🇪' },
  { code: '+30', name: 'اليونان', nameEn: 'Greece', flag: '🇬🇷' },
  { code: '+48', name: 'بولندا', nameEn: 'Poland', flag: '🇵🇱' },
  { code: '+420', name: 'التشيك', nameEn: 'Czech Republic', flag: '🇨🇿' },
  { code: '+36', name: 'المجر', nameEn: 'Hungary', flag: '🇭🇺' },
  { code: '+40', name: 'رومانيا', nameEn: 'Romania', flag: '🇷🇴' },
  { code: '+380', name: 'أوكرانيا', nameEn: 'Ukraine', flag: '🇺🇦' },
  { code: '+52', name: 'المكسيك', nameEn: 'Mexico', flag: '🇲🇽' },
  { code: '+55', name: 'البرازيل', nameEn: 'Brazil', flag: '🇧🇷' },
  { code: '+54', name: 'الأرجنتين', nameEn: 'Argentina', flag: '🇦🇷' },
  { code: '+56', name: 'تشيلي', nameEn: 'Chile', flag: '🇨🇱' },
  { code: '+57', name: 'كولومبيا', nameEn: 'Colombia', flag: '🇨🇴' },
  { code: '+51', name: 'بيرو', nameEn: 'Peru', flag: '🇵🇪' },
]

// Get country by code
export const getCountryByCode = (code) => {
  return countryCodes.find(country => country.code === code) || countryCodes[0]
}

// Default country: Saudi Arabia (platform is KSA-only)
export const getDefaultCountry = () => {
  return countryCodes[0]
}

